[package]
name = "chemapp_rs"
version = "1.0.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
authors = ["Evgenii Nekhoroshev <e.nekhoroshev@uq.edu.au>"]
repository = "https://github.com/evnekdev/chemapp_rs"
documentation = "https://docs.rs/chemapp_rs"
homepage = "https://github.com/evnekdev/chemapp_rs"
readme = "README.md"
description = "Unofficial Rust bindings and high-level interface for the ChemApp thermochemical equilibrium library"
keywords = ["chemistry", "thermodynamics", "ffi", "equilibrium", "chemapp"]
categories = ["science", "api-bindings"]
include = [
    "/src/**",
    "/examples/**/*.rs",
    "/docs/chemapp-manual/**",
    "/CHANGELOG.md",
    "/LICENSE",
    "/README.md",
]

[dependencies]
tempfile = "3.27"
lazy_static = "1.5"
libloading = "0.8"
function_name = "0.3"
nalgebra = "0.32"
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0", features = ["serde", "alloc"] }
chemformula = "0.2"
comfy-table = { version = "=7.1.4", default-features = false }
