[package]
name = "chemapp_rs"
version = "0.1.0"
edition = "2021"
author = "Evgenii Nekhoroshev e.nekhoroshev@uq.edu.au, evgnekhoroshev@gmail.com"
description = "Port of ChemApp library (GTT-technologies) for thermodynamic calculations to Rust environment; includes native ChemApp functions starting with 'tq' and a higher-level interface for easier access to calculations."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
libloading="0.7.*"
function_name = "*"
nalgebra = "0.32.*"
serde = {version = "*", features = ["derive"]}
chemformula = {path = "../chemformula"}
